services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zk
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZK_PORT:-2181}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "${ZK_PORT:-2181}:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper                       # <— nếu service ZooKeeper của bạn tên "zk"
    ports:
      - "9092:9092"              # trong Docker: các service gọi kafka:9092
      - "29092:29092"            # ngoài host/Windows: gọi localhost:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZK_PORT:-2181}"

      # MỖI listener 1 cổng KHÁC NHAU
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  hbase:
    image: harisekhon/hbase:2.0
    container_name: hbase
    depends_on: [zookeeper]
    environment:
      HBASE_MANAGES_ZK: "false"
      HBASE_ZOOKEEPER_QUORUM: zk
    ports:
      - "${HBASE_UI:-16010}:16010"   # HBase Master UI
      - "2182:2181"                  # (nội bộ HBase)
      - "${HBASE_THRIFT:-9090}:9090" # Thrift server (app/Spark ghi HBase)
    healthcheck:
      test: ["CMD-SHELL", "echo status | hbase shell -n >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 40

networks:
  bigdata-network:
    name: bigdata-network
    driver: bridge
